test:
  tags:     ON
  captcha:  ON
  sphinx:   OFF
  delayed_job: OFF

development:
  tags:     ON
  captcha:  ON
  sphinx:
    switch: ON
    if_gem: 'thinking_sphinx'
    if_file: 'log/searchd.development.pid'
  delayed_job:
    switch:  ON
    if_gem: 'delayed_job'

production:
  tags:     ON
  captcha:  ON
  sphinx:
    switch: ON
    if_gem: 'thinking_sphinx'
    if_file: 'log/searchd.production.pid'
  delayed_job:
    switch:  ON
    if_gem: 'delayed_job'
