test:
  tags:     ON
  captcha:  ON
  sphinx:   OFF
  delayed_job: OFF

development:
  tags:     ON
  captcha:  ON
  sphinx:
    switch: OFF
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.development.pid'
  delayed_job:
    switch:  OFF
    activate_if:
      gem: 'delayed_job'

production:
  tags:     ON
  captcha:  ON
  sphinx:
    switch: ON
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.production.pid'
  delayed_job:
    switch:  ON
    activate_if:
      gem: 'delayed_job'
