hpricot:
RedCloth:       '= 3.0.4'
gettext:        '= 1.93.0'
querybuilder:   '= 0.5.5'
ruby-recaptcha: '= 1.0.0'
syntax:         '= 1.0.0'
tzinfo:         '= 0.3.12'
uuidtools:      '= 2.0.0'
rmagick:        '= 2.11.1'

yamltest:
  development_only:  yes
  version: '= 0.5.3'

grosser-fast_gettext:
  lib:        'fast_gettext'
  version:    '~> 0.4.16'
  source:     'http://gems.github.com'

mislav-will_paginate:
  version:    '~> 2.2.3'
  lib:        'will_paginate'
  source:     'http://gems.github.com'

pvande-differ:
  version:    '= 0.1.1'
  lib:        'differ'
  source:     'http://gems.github.com'

thoughtbot-shoulda:
  development_only: yes
  version:    '= 2.10.2'
  lib:        'shoulda'
  source:     'http://gems.github.com'