test:
  sql_range_step: 10000000

production:
  enable_star: 1
  min_infix_len: 2
  sql_range_step: 10000000
  run_indexer_at: "10,40"

development:
  enable_star: 1
  min_infix_len: 2
  sql_range_step: 10000000